version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.django
    environment:
      DB_NAME: mongodb
      DB_HOSTNAME: 52.66.199.15
    ports:
      - 8000:8000
