version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME:  
      DB_USERNAME: 
      DB_PASSWORD: 
      DECODE_KEY: 
      SECRET_KEY: 
      DB_HOSTNAME: 52.66.199.15
    ports:
      - 8000:8000
