# Generated by Django 2.2.12 on 2020-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
