version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) 


  #####BuildingDockerfile ######
  build:
    commands:
      - echo The current build number is $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo The Commit ID is $COMMIT_HASH
      - echo The CodeBuild Number is $CODEBUILD_BUILD_NUMBER-$COMMIT_HASH
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER-$COMMIT_HASH .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER-$COMMIT_HASH $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER-$COMMIT_HASH
      - sed -i'' -e "s/latest/$CODEBUILD_BUILD_NUMBER-$COMMIT_HASH/g" eon_backend/values.yaml

#####Pushing Docker Image ####     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER-$COMMIT_HASH

artifacts:
  files:
    - '**/*'