apiVersion: v1
data:
  CLOUD_PROVIDER: aws
  DB_HOSTNAME: '{{ .Values.dbHostname }}'
  DB_NAME: '{{ .Values.dbName }}'
  DB_USERNAME: '{{ .Values.dbUsername }}'
  DB_PASSWORD: '{{ .Values.dbPassword }}'
  DECODE_KEY: '{{ .Values.decodeKey }}'
  DB_PORT: '{{ .Values.dbPort }}'
  SECRET_KEY: '{{ .Values.secretKey }}'
kind: ConfigMap
metadata:
  labels:
    service: {{ .Values.service }}
  name: {{ .Values.configmap_env }}

