apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
spec:
  ports:
    - port: {{ .Values.exposedport }}
      targetPort: {{ .Values.containerport }}
      protocol: TCP
      name: http
  type: LoadBalancer
  selector:
    app: {{ .Values.service }}
